name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup repository
      run: |
        echo "POSTGRES_USER=test
              POSTGRES_PASSWORD=test
              POSTGRES_DB=test
              POSTGRES_HOST=test

              PGADMIN_DEFAULT_EMAIL=foo@bar.com
              PGADMIN_DEFAULT_PASSWORD=foo" >> .env
    - name: Check .env file
      run: cat .env

    - name: Build the Docker image
      uses: sudo-bot/action-docker-compose@latest
      with:
    # Command line arguments
        cli-args: build --no-cache
